services:
  goai-api:
    image: golang:1.24
    container_name: goai-api
    environment:
      GOCACHE: /tmp/.cache
    ports:
      - "8089:8080"
    user: "${UID}:${GID}"
    depends_on:
      - goai-db
    volumes:
      - ./:/app
      - ${APP_PROJECT_URL}:/app-project
    working_dir: /app
    command: ["go", "run", "todos.go"]

  goai-db:
    image: mysql:8.0
    container_name: goai-db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: '${DB_NAME:-goai_db}'
      MYSQL_USER: '${DB_USER:-goai_user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - mysql_data:/var/lib/mysql

  goai-adminer:
    image: adminer
    container_name: goai-adminer
    restart: unless-stopped
    ports:
      - "8069:8080"
    depends_on:
      - goai-db

volumes:
  mysql_data:
